### ISSUE TITLE
From current "dev" branch to production

### ISSUE THREAD

**Issue by noirbizarre** [etalab/udata-gouvfr#141]
There is a lot of fixes and awaited improvements on the `dev` branch (which right now is more stable than the `master` branch).

Here's the check list to deliver it to Data.gouv.fr:

- [x] test the current master branch delivery on <https://next.data.gouv.fr>
- [x] bump the versions (udata, udata-gouvfr and all other extensions):
  - [x] udata
  - [x] udata-gouvfr
  - [x] udata-piwik
  - [x] udata-youckan
- [x] deploy the bumped version to production
- [x] merge `master` branch into the `dev` on every repository:
  - [x] udata
  - [x] udata-gouvfr
  - [x] <del>udata-piwik</del> => no changes on `dev`
  - [x] udata-youckan
- [x] merge remaining essential PRs
  - [x] opendatateam/udata-youckan#7
  - [x] opendatateam/udata#520
  - [x] opendatateam/udata#693
- [x] deploy on <https://demo.data.gouv.fr>
- [x] merge `dev` branch into the `master` on every repository:
  - [x] udata opendatateam/udata#688
  - [x] udata-gouvfr #147 
  - [x] <del>udata-piwik</del> => no changes on `dev`
  - [x] udata-youckan opendatateam/udata-youckan#13
- [x] deploy on <https://next.data.gouv.fr>
- [x] push the new content on [transifex](https://www.transifex.com/etalab/)
- [x] translate the new content on [transifex](https://www.transifex.com/etalab/)
- [x] import new translations from [transifex](https://www.transifex.com/etalab/)
- [x] deploy on <https://next.data.gouv.fr>
- [x] test, test, test, adjust, test, adjust, repeat while it's not stable
- [x] import updated and fixed translations from [transifex](https://www.transifex.com/etalab/)
- [x] bump release
- [x] perform the migration (see the changelog):
  - [x] upgrade the udata configuration
  - [x] upgrade mongo and migrate data
  - [x] upgrade ElasticSearch
    - [x] drop old indices
    - [x] reindex
- [x] celebrate (again 🙂)

**Comment by jdesboeufs** [comment]
I already tested the current https://next.data.gouv.fr ;)

**Comment by noirbizarre** [comment]
Done 🎉 🎊
